version: "3"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: pt
    restart: always
    ports:
      - "9000:9000" # Docker Deamon
      - "8000:8000" # GUI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /portainer_data:/data
