# https://github.com/nodejs/docker-node
version: '3.8'

services:
  node:
    image: node
    container_name: node
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"

