### HTTP Zertifikat
version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "tr"
    hostname: tr
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"               # gestattet http Zugriff fuer den start
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=EMAIL"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

      # Dashboard Nicht ohne "Dynamic Konfiguration" implementierbar
      #
      # Optional
      # Default: true
      #
      - "--api.dashboard=true"

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8080:8080/tcp"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"



  whoami:                       #Setzt die Domain fest
    image: "traefik/whoami"
    container_name: "tr-whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`Domain`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

