version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: tf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Konfiguration
      - /var/docker/traefik:/etc/traefik
    networks:
      - traefik_proxy
      - default
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"


networks:
  # docker network create traefik_proxy
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge