# https://hub.docker.com/r/linuxserver/plex
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - VERSION=docker
      - UMASK_SET=022
    volumes:
      - /var/lib/PlexConfig:/config
      - /srv/dev-disk-by-label-Data/Data/media/tvseries:/tv
      - /srv/dev-disk-by-label-Data/Data/media/movies:/movies
    restart: unless-stopped