# https://doc.traefik.io/traefik/user-guides/docker-compose/acme-http/
### HTTP Zertifikat
[certificatesResolvers.letsencrypt.acme]                 # Name des Anbieters
email = "<E-Mail feur Zertifizierungsstelle>"
storage = "/etc/traefik/ACME/acme.json"                  # Datei in der das Zertifikat gespeichert werden soll.
[certificatesResolvers.letsencrypt.acme.httpChallenge]   # Ausführung
entryPoint = "web"                                       # Intern genutzter Eintrittspunkt fuer das Traeffik-Dashboard

### TLS Zertifikat