version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: wt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro

    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - notification-slack-identifier=wt_Htest

#     - WATCHTOWER_CLEANUP=true
#     - WATCHTOWER_LABEL_ENABLE=true
#     - WATCHTOWER_INCLUDE_RESTARTING=true
#   labels:
#     - "com.own_name.watchtower.enable=true"
