# if ssh is disabled by default
FROM debian
RUN apt update && apt upgrade && apt install\
    openssh-server \
    \
    \
    && apt clean


# RUN ssh für Nutzer freischakten
# https://mg-it.de/blog/ssh-zugang-einrichten

