# website Dockerfile for grav Unofficial
#
# TODO dependencies
# TODO download file -> extract
#
FROM apache:latest

#LABEL maintainer "Rthem@gmx.de"
#LABEL description "Test"



RUN apt-get update -y && apt-get upgrade -y