# website Dockerfile for grav Unofficial - container wird durch dockerfile nur gebiukdet und muss dann mit compose instanziert werden
#
# TODO download file -> extract -> copy -> rm old
# create volumes for specific data
# use gantry version
#

FROM apache:latest

#LABEL maintainer "Rthem@gmx.de"
#LABEL description "Test"

RUN apt-get update -y && apt-get upgrade -y

# https://getgrav.org/download/core/grav-admin/1.7.15
